### ISSUE TITLE
Add new item to SnapshotStateList throw IndexOutOfBoundsException

### ISSUE THREAD

**Issue by sheng-ri** [Calvin-LL/Reorderable#22]
Code:
```Kotlin
@Composable
fun Test() {
    val list = remember { mutableStateListOf("1", "2") }
    Column(modifier = Modifier.fillMaxSize()) {
        ReorderableColumn(
            list = list,
            onSettle = { fromIndex, toIndex ->
                list.apply {
                    add(toIndex, removeAt(fromIndex))
                }
                // Update the list
            },
        ) { index, item, isDragging ->
            key(item) {
                Text(
                    text = item,
                    modifier = Modifier.size(40.dp)
                        .draggableHandle()
                )
            }
        }
        Button(onClick = {list.add("334")}) {
            Text("Add")
        }
    }
}


```

```Kotlin
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: index: 2, size: 2
	at androidx.compose.runtime.external.kotlinx.collections.immutable.internal.ListImplementation.checkElementIndex$runtime(ListImplementation.kt:15)
	at androidx.compose.runtime.external.kotlinx.collections.immutable.implementations.immutableList.SmallPersistentVector.get(SmallPersistentVector.kt:146)
	at androidx.compose.runtime.snapshots.SnapshotStateList.get(SnapshotStateList.kt:92)
	at sh.calvin.reorderable.ReorderableScopeImpl.draggableHandle(ReorderableList.kt:237)
	at sh.calvin.reorderable.ReorderableScope$DefaultImpls.draggableHandle$default(ReorderableList.kt:203)
	at ComposableSingletons$MainKt$lambda-1$1.invoke(main.kt:33)
	at ComposableSingletons$MainKt$lambda-1$1.invoke(main.kt:28)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:191)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at sh.calvin.reorderable.ReorderableListKt.ReorderableColumn(ReorderableList.kt:343)
	at sh.calvin.reorderable.ReorderableListKt$ReorderableColumn$3.invoke(ReorderableList.kt)
	at sh.calvin.reorderable.ReorderableListKt$ReorderableColumn$3.invoke(ReorderableList.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2557)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2828)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3315)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3266)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:940)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1155)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:127)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:583)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.scene.BaseComposeScene.render(BaseComposeScene.skiko.kt:163)
	at androidx.compose.ui.scene.ComposeSceneMediator$DesktopSkikoView.onRender(ComposeSceneMediator.desktop.kt:523)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:548)
	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invokeSuspend(Direct3DRedrawer.kt:49)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.scene.ComposeContainer$DesktopCoroutineExceptionHandler@3add0369, androidx.compose.runtime.BroadcastFrameClock@26b7c6ca, StandaloneCoroutine{Cancelling}@9b20131, FlushCoroutineDispatcher@73195de7]
```

**Comment by Calvin-LL** [comment]
Try wrapping the `mutableStateListOf` in `remember`

**Comment by sheng-ri** [comment]
> Try wrapping the `mutableStateListOf` in `remember`

This code is simplify from my code, so i lost the remember.
Sorry for that,and add remember not solve this problem.

**Comment by Calvin-LL** [comment]
I figured it out.

## Solution

Add `.toList()`

```kotlin
@Composable
fun Test() {
    val list = remember { mutableStateListOf("1", "2") }
    Column(modifier = Modifier.fillMaxSize()) {
        ReorderableColumn(
            list = list.toList(),
            onSettle = { fromIndex, toIndex ->
                list.apply {
                    add(toIndex, removeAt(fromIndex))
                }
                // Update the list
            },
        ) { index, item, isDragging ->
            key(item) {
                Text(
                    text = item,
                    modifier = Modifier.size(40.dp)
                        .draggableHandle()
                )
            }
        }
        Button(onClick = {list.add("334")}) {
            Text("Add")
        }
    }
}
```

## Reason

Looks like `SnapshotStateList` only trigger updates when a property is accessed. So the following code will only print once. 

```kotlin
@Composable
fun Test() {
    val list = remember { mutableStateListOf("1", "2") }

    LaunchedEffect(list) {
        println("list: ${list.size}")
    }

    Button(onClick = { list.add("334") }) {
        Text("Add")
    }
}
```

Where as the following piece of code will print every time the "Add" button is clicked.

```kotlin
@Composable
fun Test() {
    val list = remember { mutableStateListOf("1", "2") }

    LaunchedEffect(list.toList()) {
        println("list: ${list.size}")
    }

    Button(onClick = { list.add("334") }) {
        Text("Add")
    }
}
```
